name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Change this to your main branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install --save-dev html-minifier-terser clean-css-cli

      - name: Create minified directory
        run: mkdir -p dist

      - name: Minify CSS
        run: |
          npx cleancss -o dist/style.css style.css

      - name: Minify HTML files
        run: |
          # Copy HTML files first, then minify them one by one
          cp *.html dist/
          cd dist
          for file in *.html; do
            echo "Minifying $file..."
            npx html-minifier-terser \
              --collapse-whitespace \
              --remove-comments \
              --remove-optional-tags \
              --remove-redundant-attributes \
              --remove-script-type-attributes \
              --remove-tag-whitespace \
              --use-short-doctype \
              --minify-css true \
              --minify-js true \
              --output "$file.tmp" \
              "$file" && mv "$file.tmp" "$file"
          done

      - name: Copy static assets
        run: |
          # Copy all non-HTML/CSS files to dist
          find . -type f \
            ! -path './.git/*' \
            ! -path './node_modules/*' \
            ! -path './dist/*' \
            ! -path './.github/*' \
            ! -name '*.html' \
            ! -name 'style.css' \
            ! -name 'package*.json' \
            -exec cp --parents {} dist/ \;

      - name: Update CSS references in minified HTML
        run: |
          # Update CSS references to point to minified version
          cd dist
          sed -i 's|href="./style.css"|href="./style.css"|g' *.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4